### ISSUE TITLE
Clarification on Federal Requirements instructions

### ISSUE THREAD

**Issue by HQBD** [AlaskaDHSS/RFP-Search-Unification#15]
# Question/Comment on this Alaska DHSS RFP 180000022

## Name and affiliation
Lynda Hefner, Business Development

## Section of RFP documents
Sec. 1.08 Item (e) Federal Requirements

## Question/Comment
Instructions state, "The offeror must identify all known federal requirements that apply to the proposal, the evaluation, or the contract."
We are unclear what Item (e) requires from offerors. Is the State requiring offerors to search for all federal requirements this RFP is subject to, including your evaluation and contract process, and then list these requirements?

**Comment by randyhart** [comment]
Good question.  Item (e) certainly seems to put way too much of a burden on vendors.  We'll do some research into whether this is a mandatory clause and make adjustments if possible.

**Comment by randyhart** [comment]
We are deleting this clause as part of the next amendment. However, Offerors should be aware that there are a number of federal requirements that the Alaska product team and the awarded vendor will need to account for as the product is being developed.
