### ISSUE TITLE
Clarification on Page Limitation

### ISSUE THREAD

**Issue by HQBD** [AlaskaDHSS/RFP-Search-Unification#21]
# Question/Comment on this Alaska DHSS RFP 180000022

## Name and affiliation
Lynda Hefner, Business Development

## Section of RFP documents
7-page limitation language:  The following sections specifically state, "...is included as part of your seven-page limitation."
- Sec. 4.03 Technical Approach
- Sec. 4.06 Staffing Plan (excluding resumes and letters of intent)
- Sec. 4.07 Similar Experience and Qualifications

## Question/Comment
Based on current instructions, are the following sections **not** subject to the seven-page limitation?
- Sec. 4.02 Introduction
- Sec. 4.04 Project Management
- Sec. 4.05 Approach to User Interface and User Experience Design

**Comment by randyhart** [comment]
These sections are meant to be included in the page limitation. The RFP instructions will be amended to clarify this and to increase the page limit from 7 pages to 9 pages.
