### ISSUE TITLE
RFP Question: Latency and Data Freshness

### ISSUE THREAD

**Issue by fdesjardins** [AlaskaDHSS/RFP-Search-Unification#34]
# Question/Comment on this Alaska DHSS RFP

## Name and affiliation
Forrest Desjardins - Tech Lead at [ResourceDataInc](https://github.com/ResourceDataInc)

## Section of RFP documents
[Prototype Findings - Other Questions / Considerations](https://github.com/AlaskaDHSS/RFP-Search-Unification/blob/master/4-Prototype-Findings.md#other-questions--considerations)  

## Question/Comment
The prototype findings document mentions that latency may be a concern. We have some related questions:

- at what point does data become stale enough to require a refresh?
- how quickly will new documents/changes need to be visible in the search application?
- what was the latency for proxying to/from the existing systems found during prototyping?

**Comment by randyhart** [comment]
The latency that we're describing is network latency, and not e.g. latency in updating mirrored databases distributed physically around Alaska.

Both ARIES' and EIS' data is updated in real-time. ARIES updates are pushed to MCI in real time. EIS, on the other hand, only has its updates pushed to MCI on a daily basis. We expect searches to be run against MCI, which has an API endpoint for searches, and that there will be no delay in those records being available. Which is to say that is not likely viable to use a separate search system (e.g., ElasticSearch or Solr) to index records.

We have not tested latency from various offices to the prototype. The latency concern here is to the eventual production home.
