### ISSUE TITLE
What are the databases that the systems EIS, ARIES based on?

### ISSUE THREAD

**Issue by phcheesman** [AlaskaDHSS/RFP-Search-Unification#36]
# What are the databases that the systems EIS, ARIES are based on

## Section of RFP documents
n/a

**Comment by randyhart** [comment]
ARIES uses a Postgres database, and EIS uses an ADABAS datastore on the state's mainframe. additional detail and a discussion of prototype work to access data in these systems can be found in the [prototype findings document](https://github.com/AlaskaDHSS/RFP-Search-Unification/blob/master/4-Prototype-Findings.md#components).
