### ISSUE TITLE
Will the selected vendor be allowed to use the .NET technologies to build the system or should the vendor be using only open source technologies to build the solution?

### ISSUE THREAD

**Issue by phcheesman** [AlaskaDHSS/RFP-Search-Unification#37]
# Question/Comment on this Alaska DHSS RFP

## Question/Comment
Will the selected vendor be allowed to use the .NET technologies to build the system or should the vendor be using only open source technologies to build the solution?

**Comment by randyhart** [comment]
The technology requirements for this work are articulated [here](https://github.com/AlaskaDHSS/EIS-Modernization#technology-requirements).
