### ISSUE TITLE
URLs/links to other documents not working in RFP

### ISSUE THREAD

**Issue by phcheesman** [AlaskaDHSS/RFP-Search-Unification#38]
# Question/Comment on this Alaska DHSS RFP

## Section of RFP documents
3.01 

## Question/Comment
In section 3.01, there is a reference to additional documentation but the URL does not seem to take the reader to the referenced documents, as follows: "The State of Alaska will **provide documentation** on how to access data sources, describe existing authentication systems, and discuss how to continuously deploy work to a staging environment." Can you provide these?

**Comment by randyhart** [comment]
The documentation referenced in that section of the RFP can be found here:

[Documentation on how to access data sources](https://github.com/AlaskaDHSS/RFP-Search-Unification/blob/master/4-Prototype-Findings.md)
[Describe existing authentication systems](https://github.com/AlaskaDHSS/DevSecOpsMvp/tree/master/webseal)
[Describe how to continuously deploy work to a staging environment](https://github.com/AlaskaDHSS/DevSecOpsMvp/tree/master/vsts)
