### ISSUE TITLE
RFP Question

### ISSUE THREAD

**Issue by sylentnight83** [AlaskaDHSS/RFP-Search-Unification#39]
# Question/Comment on this Alaska DHSS RFP

## Name and affiliation
Michael Falkner, The Nerdery

## Section of RFP documents
Section 3.02 Requirements

## Question/Comment
What are the requirements for a backend API to unify MCI, ARIES, EIS, and provide SSO? Are there any documents proposing what methods and functionality would be available on the completed, unified API?

**Comment by randyhart** [comment]
The [prototype application](https://github.com/AlaskaDHSS/ProtoWebApi) provides one view of how a unified API could be structured.

The [prototype findings document](https://github.com/AlaskaDHSS/RFP-Search-Unification/blob/master/4-Prototype-Findings.md) - particularly the section on `Other Questions / Considerations` - has important information learned through the prototyping process.
