### ISSUE TITLE
Should we archive this page now that the RFP and contract are over?

### ISSUE THREAD

**Issue by randyhart** [AlaskaDHSS/RFP-Search-Unification#66]

**Comment by nfaulknerAK** [comment]
I think we are good to archive. There are no open issues or PR's that I am aware of. Archiving will not allow us to add any contributors or teams, which I think is fine in this case. @robjohnsonakgov do you have any reason to keep this live?

**Comment by robjohnsonakgov** [comment]
I have no reason to keep this live – want me to archive or do you have the right permissions to do that?

**Comment by randyhart** [comment]
ok. I'm going to send you all a PR that cleans up some of the readme, then we can archive.
